services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: cyberbro
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: always
    volumes:
      - ./data:/app/data