name: Build and Publish Docker image on GitHub Container Registry

on:
  push:
    branches:
      - advanced-config

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.DEPLOYMENT_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        env:
          GUI_ENABLED_ENGINES: "reverse_dns,rdap,ipquery,abuseipdb,virustotal,spur,google_safe_browsing,shodan,phishtank,threatfox,urlscan,google,github,opencti,abusix,hudsonrock"
        run: docker build -t ghcr.io/${{ github.repository_owner }}/cyberbro:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/cyberbro:latest
